
server:
  port: 9080

spring:
  application:
    name: unit-conversion-service

logging:
  level:
    root: INFO
    com.example.unit conversion: DEBUG


# datasource:
#   url: jdbc:mysql://localhost:3306/interconversion
#   username: host
#   password: Tejas@1410
#   driver-class-name: com.mysql.cj.jdbc.Driver
#   hikari:
#     maximum-pool-size: 10
#
#
# security:
#   basic:
#     enabled: false



