
server:
  port: 9004

spring:
  application:
    name: unit-conversion-service

logging:
  level:
    root: INFO
    com.example.unit conversion: DEBUG

# Additional configuration can be added here as needed

# Uncomment and configure this section if you have database settings
# datasource:
#   url: jdbc:mysql://localhost:3306/unitconversiondb
#   username: yourusername
#   password: yourpassword
#   driver-class-name: com.mysql.cj.jdbc.Driver
#   hikari:
#     maximum-pool-size: 10

# Uncomment and configure this section if you have specific security settings
# security:
#   basic:
#     enabled: false

# Additional configurations can be added as needed

